spring.application.name=ticketbooking

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketbooking
spring.datasource.username=ticketbooking
spring.datasource.password=test

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false