-- =========================================================
-- V1__initial_schema.sql
-- Initial schema for Ticket Booking System
-- =========================================================

-- Required for PostgreSQL exclusion constraints involving
-- BIGINT equality + GiST.
CREATE EXTENSION IF NOT EXISTS btree_gist;


-- =========================================================
-- MOVIES
-- =========================================================

CREATE TABLE movies (
    movie_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_name       VARCHAR(200) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    genre             VARCHAR(50) NOT NULL,
    parental_rating  VARCHAR(10) NOT NULL,
    language          VARCHAR(50) NOT NULL,
    release_date     DATE NOT NULL,

    CONSTRAINT chk_movie_duration
        CHECK (duration_minutes > 0)
);


-- =========================================================
-- THEATERS
-- =========================================================

CREATE TABLE theaters (
    theater_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(50)  NOT NULL,
    city       VARCHAR(50)  NOT NULL,
    address    VARCHAR(500) NOT NULL
);


-- =========================================================
-- SCREENS
-- =========================================================

CREATE TABLE screens (
    screen_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theater_id  BIGINT      NOT NULL,
    screen_name VARCHAR(50) NOT NULL,
    screen_type VARCHAR(50) NOT NULL,

    CONSTRAINT fk_screen_theater
        FOREIGN KEY (theater_id)
        REFERENCES theaters(theater_id),

    CONSTRAINT uk_theater_screen_name
        UNIQUE (theater_id, screen_name)
);


-- =========================================================
-- SEATS
-- =========================================================

CREATE TABLE seats (
    seat_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id   BIGINT      NOT NULL,
    row_label   VARCHAR(2)  NOT NULL,
    seat_number INTEGER     NOT NULL,
    seat_type   VARCHAR(20) NOT NULL,

    CONSTRAINT fk_seat_screen
        FOREIGN KEY (screen_id)
        REFERENCES screens(screen_id),

    CONSTRAINT uk_screen_seat
        UNIQUE (screen_id, row_label, seat_number),

    CONSTRAINT chk_seat_number
        CHECK (seat_number > 0)
);


-- =========================================================
-- SHOWS
-- =========================================================

CREATE TABLE shows (
    show_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id   BIGINT      NOT NULL,
    screen_id  BIGINT      NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time   TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_show_movie
        FOREIGN KEY (movie_id)
        REFERENCES movies(movie_id),

    CONSTRAINT fk_show_screen
        FOREIGN KEY (screen_id)
        REFERENCES screens(screen_id),

    CONSTRAINT chk_show_time
        CHECK (end_time > start_time),

    CONSTRAINT uk_screen_show_no_overlap
        EXCLUDE USING GIST (
            screen_id WITH =,
            tstzrange(start_time, end_time, '[)') WITH &&
        )
);


-- =========================================================
-- SHOW SEATS
-- =========================================================

CREATE TABLE show_seats (
    show_seat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id      BIGINT         NOT NULL,
    seat_id      BIGINT         NOT NULL,
    status       VARCHAR(20)    NOT NULL,
    base_price   NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_show_seat_show
        FOREIGN KEY (show_id)
        REFERENCES shows(show_id),

    CONSTRAINT fk_show_seat_seat
        FOREIGN KEY (seat_id)
        REFERENCES seats(seat_id),

    CONSTRAINT uk_show_seat
        UNIQUE (show_id, seat_id),

    CONSTRAINT chk_show_seat_status
        CHECK (status IN ('AVAILABLE', 'HELD', 'BOOKED')),

    CONSTRAINT chk_show_seat_price
        CHECK (base_price >= 0)
);


-- =========================================================
-- BOOKINGS
-- =========================================================

CREATE TABLE bookings (
    booking_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name  VARCHAR(150)  NOT NULL,
    show_id        BIGINT        NOT NULL,
    booking_status VARCHAR(30)   NOT NULL,
    total_amount   NUMERIC(12,2) NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL,

    CONSTRAINT fk_booking_show
        FOREIGN KEY (show_id)
        REFERENCES shows(show_id),

    CONSTRAINT chk_booking_status
        CHECK (
            booking_status IN (
                'CREATED',
                'PAYMENT_PENDING',
                'CONFIRMED',
                'EXPIRED',
                'CANCELLED'
            )
        ),

    CONSTRAINT chk_booking_total
        CHECK (total_amount >= 0)
);


-- =========================================================
-- BOOKING SEATS
-- =========================================================

CREATE TABLE booking_seats (
    booking_seat_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id       BIGINT         NOT NULL,
    show_seat_id     BIGINT         NOT NULL,
    price_at_booking NUMERIC(12,2)  NOT NULL,
    discount_amount  NUMERIC(12,2)  NOT NULL,
    final_price      NUMERIC(12,2)  NOT NULL,

    CONSTRAINT fk_booking_seat_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id),

    CONSTRAINT fk_booking_seat_show_seat
        FOREIGN KEY (show_seat_id)
        REFERENCES show_seats(show_seat_id),

    CONSTRAINT uk_booking_show_seat
        UNIQUE (booking_id, show_seat_id),

    CONSTRAINT chk_booking_seat_price
        CHECK (price_at_booking >= 0),

    CONSTRAINT chk_booking_seat_discount
        CHECK (discount_amount >= 0),

    CONSTRAINT chk_booking_seat_final_price
        CHECK (final_price >= 0)
);


-- =========================================================
-- PAYMENTS
-- =========================================================

CREATE TABLE payments (
    payment_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    BIGINT         NOT NULL,
    amount        NUMERIC(12,2)  NOT NULL,
    payment_mode  VARCHAR(30)    NOT NULL,
    payment_status VARCHAR(30)   NOT NULL,
    created_at    TIMESTAMPTZ    NOT NULL,

    CONSTRAINT fk_payment_booking
        FOREIGN KEY (booking_id)
        REFERENCES bookings(booking_id),

    CONSTRAINT chk_payment_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payment_mode
        CHECK (
            payment_mode IN (
                'CARD',
                'UPI',
                'NET_BANKING',
                'WALLET'
            )
        ),

    CONSTRAINT chk_payment_status
        CHECK (
            payment_status IN (
                'PENDING',
                'SUCCESS',
                'FAILED'
            )
        )
);


-- =========================================================
-- INDEXES
-- =========================================================

CREATE INDEX idx_shows_movie_start_time
    ON shows(movie_id, start_time);

CREATE INDEX idx_shows_screen_start_time
    ON shows(screen_id, start_time);

CREATE INDEX idx_show_seats_show_status
    ON show_seats(show_id, status);

CREATE INDEX idx_booking_seats_booking
    ON booking_seats(booking_id);

CREATE INDEX idx_payments_booking
    ON payments(booking_id);


-- =========================================================
-- PAYMENT INVARIANT
-- At most one successful payment per booking
-- =========================================================

CREATE UNIQUE INDEX uk_one_successful_payment_per_booking
    ON payments(booking_id)
    WHERE payment_status = 'SUCCESS';